name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm run test --if-present

      - name: Prepare For Deployment
        run: |
          cp package.json ./dist
          cp package-lock.json ./dist

      - name: Log Dist Directory (Before Upload)
        run: |
          echo "Contents of dist directory before upload:"
          ls -al ./dist

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production

    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Log Dist Directory (After Download)
        run: |
          echo "Contents of dist directory after download:"
          ls -al ./dist

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Dependencies
        working-directory: dist
        run: npm install

      - name: Deploy To Azure Web App Using Kudu
        run: |
          TOKEN=$(az account get-access-token --query accessToken -o tsv)
          curl -X POST -H "Authorization: Bearer $TOKEN" -F "path=site/wwwroot" -F "file=@./dist" https://monday-server.scm.azurewebsites.net/api/zipdeploy

      - name: Fetch Deployment Logs
        run: |
          az webapp log deployment show --resource-group monday-interview --name monday-server
