name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm run test --if-present

      - name: Prepare For Deployment
        run: |
          mkdir -p ./deploy
          cp -r ./dist/* ./deploy/
          cp package.json ./deploy/
          cp package-lock.json ./deploy/

      - name: Log Deploy Directory (Before Upload)
        run: |
          echo "Contents of deploy directory before upload:"
          ls -al ./deploy

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./deploy

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production

    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./deploy

      - name: Log Deploy Directory (After Download)
        run: |
          echo "Contents of deploy directory after download:"
          ls -al ./deploy

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip the deploy folder
        run: |
          cd ./deploy
          zip -r ../deploy.zip .

      - name: Deploy To Azure Web App
        id: DeployToAzureWebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: monday-server
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deploy.zip

      - name: Fetch Deployment Logs
        run: |
          az webapp log deployment show --resource-group monday-interview --name monday-server
