name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm run test --if-present

      - name: Prepare For Deployment
        run: |
          mkdir -p deploy
          rsync -av --exclude='deploy' . ./deploy/
          cp -r ./dist/* ./deploy

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./deploy
          if-no-files-found: error

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production

    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: deploy_artifact

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy To Azure Web App Using Kudu
        run: |
          TOKEN=$(az account get-access-token --query accessToken -o tsv)
          cd deploy_artifact
          zip -r ../deploy_artifact.zip .
          cd ..
          curl -X POST -H "Authorization: Bearer $TOKEN" -F "file=@deploy_artifact.zip" https://monday-server.scm.azurewebsites.net/api/zipdeploy
