name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm run test --if-present

      - name: Prepare For Deployment
        run: |
          cp package.json ./dist
          cp package-lock.json ./dist

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./dist
          if-no-files-found: error

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production
      url: ${{ steps.DeployToAzureWebApp.outputs.webapp-url }}

    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./dist

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Downloaded Artifact
        run: |
          echo "Contents of downloaded artifact:"
          ls -R dist

      - name: Install Dependencies
        run: |
          cd ./dist
          npm ci

      - name: Deploy To Azure Web App
        id: DeployToAzureWebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: LingoLinkAPI
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./dist

#      - name: Verify wwwroot Directory Contents
#        run: |
#          curl -X GET -H "Authorization: Bearer $TOKEN" https://monday-server.scm.azurewebsites.net/api/zipdeploy/wwwroot
