name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Run Tests
        run: npm run test --if-present

      - name: Prepare For Deployment
        run: |
          mkdir -p deploy
          cp -r package.json package-lock.json src dist/* deploy/
          cd deploy
          zip -r ../deploy.zip .
          cd ..

      - name: Verify Deploy Zip
        run: |
          echo "Contents of deploy.zip:"
          unzip -l deploy.zip
          ls -al deploy.zip

      - name: Upload Artifact For Deployment Job
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: deploy.zip

  deploy_application:
    runs-on: ubuntu-latest
    needs: build_application
    name: Deploy Application
    environment:
      name: Production

    steps:
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v2
        with:
          name: build
          path: deploy.zip

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy To Azure Web App Using Kudu
        run: |
          az webapp deploy --resource-group monday-interview --name monday-server --src-path $(pwd)/deploy.zip --type zip

      - name: Fetch Deployment Logs
        run: |
          az webapp log deployment show --resource-group monday-interview --name monday-server
